package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AboutPage;
  private ConceptPresentation props_AvatarCard;
  private ConceptPresentation props_ContactPage;
  private ConceptPresentation props_ContentPage;
  private ConceptPresentation props_Field;
  private ConceptPresentation props_Footer;
  private ConceptPresentation props_From;
  private ConceptPresentation props_GridCard;
  private ConceptPresentation props_GridElement;
  private ConceptPresentation props_ICardConcept;
  private ConceptPresentation props_IPageConcept;
  private ConceptPresentation props_Layout;
  private ConceptPresentation props_NavBar;
  private ConceptPresentation props_PageElement;
  private ConceptPresentation props_PaginatedCard;
  private ConceptPresentation props_PersonalPortfolio;
  private ConceptPresentation props_Platform;
  private ConceptPresentation props_Project;
  private ConceptPresentation props_ProjectsPage;
  private ConceptPresentation props_Qualification;
  private ConceptPresentation props_QualificationsPage;
  private ConceptPresentation props_Social;
  private ConceptPresentation props_Technology;
  private ConceptPresentation props_Video;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AboutPage:
        if (props_AboutPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to desctibe the about page of the web app, the page contains cards and an optional timeline element.");
          cpb.rawPresentation("AboutPage");
          props_AboutPage = cpb.create();
        }
        return props_AboutPage;
      case LanguageConceptSwitch.AvatarCard:
        if (props_AvatarCard == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Card displaying text on the right side and an avatar image on the left side");
          cpb.rawPresentation("AvatarCard");
          props_AvatarCard = cpb.create();
        }
        return props_AvatarCard;
      case LanguageConceptSwitch.ContactPage:
        if (props_ContactPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to represent a page with a contact form and optional social media links.");
          cpb.rawPresentation("ContactPage");
          props_ContactPage = cpb.create();
        }
        return props_ContactPage;
      case LanguageConceptSwitch.ContentPage:
        if (props_ContentPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a basic page with markdown content.");
          cpb.rawPresentation("ContentPage");
          props_ContentPage = cpb.create();
        }
        return props_ContentPage;
      case LanguageConceptSwitch.Field:
        if (props_Field == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a filed in a contact form");
          cpb.rawPresentation("Field");
          props_Field = cpb.create();
        }
        return props_Field;
      case LanguageConceptSwitch.Footer:
        if (props_Footer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe the footer of the web page.");
          cpb.rawPresentation("Footer");
          props_Footer = cpb.create();
        }
        return props_Footer;
      case LanguageConceptSwitch.From:
        if (props_From == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("From");
          props_From = cpb.create();
        }
        return props_From;
      case LanguageConceptSwitch.GridCard:
        if (props_GridCard == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Card displaying elements in a grid format");
          cpb.rawPresentation("GridCard");
          props_GridCard = cpb.create();
        }
        return props_GridCard;
      case LanguageConceptSwitch.GridElement:
        if (props_GridElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Element including an image and a title");
          cpb.rawPresentation("GridElement");
          props_GridElement = cpb.create();
        }
        return props_GridElement;
      case LanguageConceptSwitch.ICardConcept:
        if (props_ICardConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ICardConcept = cpb.create();
        }
        return props_ICardConcept;
      case LanguageConceptSwitch.IPageConcept:
        if (props_IPageConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_IPageConcept = cpb.create();
        }
        return props_IPageConcept;
      case LanguageConceptSwitch.Layout:
        if (props_Layout == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe the basic layout components of the web page.");
          cpb.rawPresentation("Layout");
          props_Layout = cpb.create();
        }
        return props_Layout;
      case LanguageConceptSwitch.NavBar:
        if (props_NavBar == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe the nav bar of the web page.");
          cpb.rawPresentation("NavBar");
          props_NavBar = cpb.create();
        }
        return props_NavBar;
      case LanguageConceptSwitch.PageElement:
        if (props_PageElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used for displaying carousel page elements");
          cpb.rawPresentation("PageElement");
          props_PageElement = cpb.create();
        }
        return props_PageElement;
      case LanguageConceptSwitch.PaginatedCard:
        if (props_PaginatedCard == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Card displaying pages on a carousel");
          cpb.rawPresentation("PaginatedCard");
          props_PaginatedCard = cpb.create();
        }
        return props_PaginatedCard;
      case LanguageConceptSwitch.PersonalPortfolio:
        if (props_PersonalPortfolio == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Root Node for describing a Personal Portfolio webpage.");
          cpb.presentationByName();
          props_PersonalPortfolio = cpb.create();
        }
        return props_PersonalPortfolio;
      case LanguageConceptSwitch.Platform:
        if (props_Platform == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a social media platform.");
          cpb.presentationByName();
          props_Platform = cpb.create();
        }
        return props_Platform;
      case LanguageConceptSwitch.Project:
        if (props_Project == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a project.");
          cpb.rawPresentation("Project");
          props_Project = cpb.create();
        }
        return props_Project;
      case LanguageConceptSwitch.ProjectsPage:
        if (props_ProjectsPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a page displaying personal projects.");
          cpb.rawPresentation("ProjectsPage");
          props_ProjectsPage = cpb.create();
        }
        return props_ProjectsPage;
      case LanguageConceptSwitch.Qualification:
        if (props_Qualification == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to capture qualification data.");
          cpb.rawPresentation("Qualification");
          props_Qualification = cpb.create();
        }
        return props_Qualification;
      case LanguageConceptSwitch.QualificationsPage:
        if (props_QualificationsPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a page displaying qualifications in a pdf format.");
          cpb.rawPresentation("QualificationsPage");
          props_QualificationsPage = cpb.create();
        }
        return props_QualificationsPage;
      case LanguageConceptSwitch.Social:
        if (props_Social == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe all of your social contacts, such as social media sites and email address.");
          cpb.rawPresentation("Social");
          props_Social = cpb.create();
        }
        return props_Social;
      case LanguageConceptSwitch.Technology:
        if (props_Technology == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a technology.");
          cpb.rawPresentation("Technology");
          props_Technology = cpb.create();
        }
        return props_Technology;
      case LanguageConceptSwitch.Video:
        if (props_Video == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Used to describe a video");
          cpb.rawPresentation("Video");
          props_Video = cpb.create();
        }
        return props_Video;
    }
    return null;
  }
}
