package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ProjectStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ProjectStatus() {
    super(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaf7L, "ProjectStatus", "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741751");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_IN_PROGRESS_0 = new EnumerationDescriptor.MemberDescriptor("IN_PROGRESS", "in_progress", 0x67a6ba169d01eaf9L, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741753");
  private final EnumerationDescriptor.MemberDescriptor myMember_COMPLETED_0 = new EnumerationDescriptor.MemberDescriptor("COMPLETED", "completed", 0x67a6ba169d01eaf8L, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741752");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaf7L, 0x67a6ba169d01eaf9L, 0x67a6ba169d01eaf8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_IN_PROGRESS_0, myMember_COMPLETED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "IN_PROGRESS":
        return myMember_IN_PROGRESS_0;
      case "COMPLETED":
        return myMember_COMPLETED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
