package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NavBarType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NavBarType() {
    super(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d02436bL, "NavBarType", "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326764395");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_INLINE_0 = new EnumerationDescriptor.MemberDescriptor("INLINE", "inline", 0x67a6ba169d02436dL, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326764397");
  private final EnumerationDescriptor.MemberDescriptor myMember_SIDEBAR_0 = new EnumerationDescriptor.MemberDescriptor("SIDEBAR", "sidebar", 0x67a6ba169d02436cL, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326764396");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d02436bL, 0x67a6ba169d02436dL, 0x67a6ba169d02436cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_INLINE_0, myMember_SIDEBAR_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "INLINE":
        return myMember_INLINE_0;
      case "SIDEBAR":
        return myMember_SIDEBAR_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
