package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Theme extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Theme() {
    super(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5e2L, "Theme", "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744546");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_DARK_0 = new EnumerationDescriptor.MemberDescriptor("DARK", "dark", 0x67a6ba169d01f5e3L, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744547");
  private final EnumerationDescriptor.MemberDescriptor myMember_LIGHT_0 = new EnumerationDescriptor.MemberDescriptor("LIGHT", "light", 0x67a6ba169d01f5e4L, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744548");
  private final EnumerationDescriptor.MemberDescriptor myMember_TOGGLE_0 = new EnumerationDescriptor.MemberDescriptor("TOGGLE", "toggle", 0x67a6ba169d01f5e5L, "r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744549");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5e2L, 0x67a6ba169d01f5e3L, 0x67a6ba169d01f5e4L, 0x67a6ba169d01f5e5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_DARK_0, myMember_LIGHT_0, myMember_TOGGLE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "DARK":
        return myMember_DARK_0;
      case "LIGHT":
        return myMember_LIGHT_0;
      case "TOGGLE":
        return myMember_TOGGLE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
