package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AboutPage = 0;
  public static final int AvatarCard = 1;
  public static final int ContactPage = 2;
  public static final int ContentPage = 3;
  public static final int Field = 4;
  public static final int Footer = 5;
  public static final int Form = 6;
  public static final int GridCard = 7;
  public static final int GridElement = 8;
  public static final int ICardConcept = 9;
  public static final int IPageConcept = 10;
  public static final int Layout = 11;
  public static final int NavBar = 12;
  public static final int PageElement = 13;
  public static final int PaginatedCard = 14;
  public static final int PersonalPortfolio = 15;
  public static final int Platform = 16;
  public static final int Project = 17;
  public static final int ProjectsPage = 18;
  public static final int Qualification = 19;
  public static final int QualificationsPage = 20;
  public static final int Social = 21;
  public static final int Technology = 22;
  public static final int Timeline = 23;
  public static final int TimelineElement = 24;
  public static final int Video = 25;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5eee97a4f53b4a19L, 0xa155bca310393580L);
    builder.put(0x67a6ba169d01eabcL, AboutPage);
    builder.put(0x67a6ba169d01eac6L, AvatarCard);
    builder.put(0x67a6ba169d01f60dL, ContactPage);
    builder.put(0x67a6ba169d01eab6L, ContentPage);
    builder.put(0x67a6ba169d01f625L, Field);
    builder.put(0x67a6ba169d01eaa8L, Footer);
    builder.put(0x67a6ba169d01f612L, Form);
    builder.put(0x67a6ba169d01eaceL, GridCard);
    builder.put(0x67a6ba169d01ead3L, GridElement);
    builder.put(0x67a6ba169d01eac1L, ICardConcept);
    builder.put(0x67a6ba169d01eab0L, IPageConcept);
    builder.put(0x67a6ba169d01ea8fL, Layout);
    builder.put(0x67a6ba169d01ea9aL, NavBar);
    builder.put(0x67a6ba169d01eae2L, PageElement);
    builder.put(0x67a6ba169d01eadcL, PaginatedCard);
    builder.put(0x67a6ba169d012769L, PersonalPortfolio);
    builder.put(0x67a6ba169d01ea74L, Platform);
    builder.put(0x67a6ba169d01eaecL, Project);
    builder.put(0x67a6ba169d01eae8L, ProjectsPage);
    builder.put(0x67a6ba169d01f604L, Qualification);
    builder.put(0x67a6ba169d01f601L, QualificationsPage);
    builder.put(0x67a6ba169d01ea6bL, Social);
    builder.put(0x67a6ba169d01f5f7L, Technology);
    builder.put(0x757dc08330fab9eeL, Timeline);
    builder.put(0x757dc08330fab9f2L, TimelineElement);
    builder.put(0x67a6ba169d01f5f2L, Video);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
