package PersonalPortfolio.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAboutPage = createDescriptorForAboutPage();
  /*package*/ final ConceptDescriptor myConceptAvatarCard = createDescriptorForAvatarCard();
  /*package*/ final ConceptDescriptor myConceptContactPage = createDescriptorForContactPage();
  /*package*/ final ConceptDescriptor myConceptContentPage = createDescriptorForContentPage();
  /*package*/ final ConceptDescriptor myConceptField = createDescriptorForField();
  /*package*/ final ConceptDescriptor myConceptFooter = createDescriptorForFooter();
  /*package*/ final ConceptDescriptor myConceptFrom = createDescriptorForFrom();
  /*package*/ final ConceptDescriptor myConceptGridCard = createDescriptorForGridCard();
  /*package*/ final ConceptDescriptor myConceptGridElement = createDescriptorForGridElement();
  /*package*/ final ConceptDescriptor myConceptICardConcept = createDescriptorForICardConcept();
  /*package*/ final ConceptDescriptor myConceptIPageConcept = createDescriptorForIPageConcept();
  /*package*/ final ConceptDescriptor myConceptLayout = createDescriptorForLayout();
  /*package*/ final ConceptDescriptor myConceptNavBar = createDescriptorForNavBar();
  /*package*/ final ConceptDescriptor myConceptPageElement = createDescriptorForPageElement();
  /*package*/ final ConceptDescriptor myConceptPaginatedCard = createDescriptorForPaginatedCard();
  /*package*/ final ConceptDescriptor myConceptPersonalPortfolio = createDescriptorForPersonalPortfolio();
  /*package*/ final ConceptDescriptor myConceptPlatform = createDescriptorForPlatform();
  /*package*/ final ConceptDescriptor myConceptProject = createDescriptorForProject();
  /*package*/ final ConceptDescriptor myConceptProjectsPage = createDescriptorForProjectsPage();
  /*package*/ final ConceptDescriptor myConceptQualification = createDescriptorForQualification();
  /*package*/ final ConceptDescriptor myConceptQualificationsPage = createDescriptorForQualificationsPage();
  /*package*/ final ConceptDescriptor myConceptSocial = createDescriptorForSocial();
  /*package*/ final ConceptDescriptor myConceptTechnology = createDescriptorForTechnology();
  /*package*/ final ConceptDescriptor myConceptVideo = createDescriptorForVideo();
  /*package*/ final EnumerationDescriptor myEnumerationNavBarType = new EnumerationDescriptor_NavBarType();
  /*package*/ final EnumerationDescriptor myEnumerationProjectStatus = new EnumerationDescriptor_ProjectStatus();
  /*package*/ final EnumerationDescriptor myEnumerationTheme = new EnumerationDescriptor_Theme();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAboutPage, myConceptAvatarCard, myConceptContactPage, myConceptContentPage, myConceptField, myConceptFooter, myConceptFrom, myConceptGridCard, myConceptGridElement, myConceptICardConcept, myConceptIPageConcept, myConceptLayout, myConceptNavBar, myConceptPageElement, myConceptPaginatedCard, myConceptPersonalPortfolio, myConceptPlatform, myConceptProject, myConceptProjectsPage, myConceptQualification, myConceptQualificationsPage, myConceptSocial, myConceptTechnology, myConceptVideo);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AboutPage:
        return myConceptAboutPage;
      case LanguageConceptSwitch.AvatarCard:
        return myConceptAvatarCard;
      case LanguageConceptSwitch.ContactPage:
        return myConceptContactPage;
      case LanguageConceptSwitch.ContentPage:
        return myConceptContentPage;
      case LanguageConceptSwitch.Field:
        return myConceptField;
      case LanguageConceptSwitch.Footer:
        return myConceptFooter;
      case LanguageConceptSwitch.From:
        return myConceptFrom;
      case LanguageConceptSwitch.GridCard:
        return myConceptGridCard;
      case LanguageConceptSwitch.GridElement:
        return myConceptGridElement;
      case LanguageConceptSwitch.ICardConcept:
        return myConceptICardConcept;
      case LanguageConceptSwitch.IPageConcept:
        return myConceptIPageConcept;
      case LanguageConceptSwitch.Layout:
        return myConceptLayout;
      case LanguageConceptSwitch.NavBar:
        return myConceptNavBar;
      case LanguageConceptSwitch.PageElement:
        return myConceptPageElement;
      case LanguageConceptSwitch.PaginatedCard:
        return myConceptPaginatedCard;
      case LanguageConceptSwitch.PersonalPortfolio:
        return myConceptPersonalPortfolio;
      case LanguageConceptSwitch.Platform:
        return myConceptPlatform;
      case LanguageConceptSwitch.Project:
        return myConceptProject;
      case LanguageConceptSwitch.ProjectsPage:
        return myConceptProjectsPage;
      case LanguageConceptSwitch.Qualification:
        return myConceptQualification;
      case LanguageConceptSwitch.QualificationsPage:
        return myConceptQualificationsPage;
      case LanguageConceptSwitch.Social:
        return myConceptSocial;
      case LanguageConceptSwitch.Technology:
        return myConceptTechnology;
      case LanguageConceptSwitch.Video:
        return myConceptVideo;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationNavBarType, myEnumerationProjectStatus, myEnumerationTheme);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAboutPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "AboutPage", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eabcL);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741692");
    b.version(3);
    b.aggregate("cards", 0x67a6ba169d01eadaL).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac1L).optional(true).ordered(true).multiple(true).origin("7468861638326741722").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAvatarCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "AvatarCard", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac6L);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac1L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741702");
    b.version(3);
    b.property("avatar", 0x67a6ba169d01eacaL).type(PrimitiveTypeId.STRING).origin("7468861638326741706").done();
    b.property("content", 0x67a6ba169d01eacbL).type(PrimitiveTypeId.STRING).origin("7468861638326741707").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContactPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "ContactPage", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f60dL);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744589");
    b.version(3);
    b.aggregate("form", 0x67a6ba169d01f613L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f612L).optional(false).ordered(true).multiple(false).origin("7468861638326744595").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForContentPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "ContentPage", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab6L);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741686");
    b.version(3);
    b.property("title", 0x67a6ba169d01eabaL).type(PrimitiveTypeId.STRING).origin("7468861638326741690").done();
    b.property("content", 0x67a6ba169d01eabbL).type(PrimitiveTypeId.STRING).origin("7468861638326741691").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Field", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f625L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744613");
    b.version(3);
    b.property("title", 0x67a6ba169d01f627L).type(PrimitiveTypeId.STRING).origin("7468861638326744615").done();
    b.property("hint", 0x67a6ba169d01f628L).type(PrimitiveTypeId.STRING).origin("7468861638326744616").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFooter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Footer", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaa8L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741672");
    b.version(3);
    b.property("show_contact_email", 0x67a6ba169d01eaaaL).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741674").done();
    b.property("show_platforms", 0x67a6ba169d01eaaeL).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741678").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFrom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "From", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f612L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744594");
    b.version(3);
    b.property("title", 0x67a6ba169d01f615L).type(PrimitiveTypeId.STRING).origin("7468861638326744597").done();
    b.property("mailjs_service_id", 0x67a6ba169d01f616L).type(PrimitiveTypeId.STRING).origin("7468861638326744598").done();
    b.property("mailjs_template_id", 0x67a6ba169d01f619L).type(PrimitiveTypeId.STRING).origin("7468861638326744601").done();
    b.property("mailjs_public_key", 0x67a6ba169d01f61bL).type(PrimitiveTypeId.STRING).origin("7468861638326744603").done();
    b.property("success_text", 0x67a6ba169d01f61dL).type(PrimitiveTypeId.STRING).origin("7468861638326744605").done();
    b.property("failure_text", 0x67a6ba169d01f621L).type(PrimitiveTypeId.STRING).origin("7468861638326744609").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGridCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "GridCard", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaceL);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac1L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741710");
    b.version(3);
    b.aggregate("grid_elements", 0x67a6ba169d01ead1L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ead3L).optional(true).ordered(true).multiple(true).origin("7468861638326741713").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForGridElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "GridElement", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ead3L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741715");
    b.version(3);
    b.property("image", 0x67a6ba169d01ead6L).type(PrimitiveTypeId.STRING).origin("7468861638326741718").done();
    b.property("title", 0x67a6ba169d01ead7L).type(PrimitiveTypeId.STRING).origin("7468861638326741719").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForICardConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "ICardConcept", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac1L);
    b.interface_();
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741697");
    b.version(3);
    b.property("title", 0x67a6ba169d01eac3L).type(PrimitiveTypeId.STRING).origin("7468861638326741699").done();
    b.property("subtitle", 0x67a6ba169d01eac4L).type(PrimitiveTypeId.STRING).origin("7468861638326741700").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIPageConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "IPageConcept", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.interface_();
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741680");
    b.version(3);
    b.property("route", 0x67a6ba169d01eab1L).type(PrimitiveTypeId.STRING).origin("7468861638326741681").done();
    b.property("nav_bar", 0x67a6ba169d01eab2L).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741682").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLayout() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Layout", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea8fL);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741647");
    b.version(3);
    b.property("animated_stars_background", 0x67a6ba169d01ea91L).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741649").done();
    b.property("theme", 0x67a6ba169d01ea93L).type(MetaIdFactory.dataTypeId(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5e2L)).origin("7468861638326741651").done();
    b.aggregate("navbar", 0x67a6ba169d01eaa5L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea9aL).optional(false).ordered(true).multiple(false).origin("7468861638326741669").done();
    b.aggregate("footer", 0x67a6ba169d01eaa7L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaa8L).optional(true).ordered(true).multiple(false).origin("7468861638326741671").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNavBar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "NavBar", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea9aL);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741658");
    b.version(3);
    b.property("type", 0x67a6ba169d01ea9dL).type(MetaIdFactory.dataTypeId(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d02436bL)).origin("7468861638326741661").done();
    b.property("show_name", 0x67a6ba169d01ea9fL).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741663").done();
    b.property("show_title", 0x67a6ba169d01eaa1L).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741665").done();
    b.property("show_logo", 0x67a6ba169d01eaa3L).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741667").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "PageElement", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eae2L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741730");
    b.version(3);
    b.property("image", 0x67a6ba169d01eae4L).type(PrimitiveTypeId.STRING).origin("7468861638326741732").done();
    b.property("content", 0x67a6ba169d01eae5L).type(PrimitiveTypeId.STRING).origin("7468861638326741733").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPaginatedCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "PaginatedCard", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eadcL);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eac1L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741724");
    b.version(3);
    b.aggregate("pages", 0x67a6ba169d01eae0L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eae2L).optional(true).ordered(true).multiple(true).origin("7468861638326741728").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPersonalPortfolio() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "PersonalPortfolio", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d012769L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326691689");
    b.version(3);
    b.property("profession", 0x67a6ba169d012907L).type(PrimitiveTypeId.STRING).origin("7468861638326692103").done();
    b.property("title", 0x67a6ba169d012909L).type(PrimitiveTypeId.STRING).origin("7468861638326692105").done();
    b.property("logo", 0x67a6ba169d01290bL).type(PrimitiveTypeId.STRING).origin("7468861638326692107").done();
    b.property("description", 0x67a6ba169d01290dL).type(PrimitiveTypeId.STRING).origin("7468861638326692109").done();
    b.property("assets_folder", 0x67a6ba169d012910L).type(PrimitiveTypeId.STRING).origin("7468861638326692112").done();
    b.aggregate("social", 0x67a6ba169d01ea85L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea6bL).optional(false).ordered(true).multiple(false).origin("7468861638326741637").done();
    b.aggregate("layout", 0x67a6ba169d01ea8eL).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea8fL).optional(false).ordered(true).multiple(false).origin("7468861638326741646").done();
    b.aggregate("pages", 0x67a6ba169d01eab4L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L).optional(true).ordered(true).multiple(true).origin("7468861638326741684").done();
    b.alias("Portfolio");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPlatform() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Platform", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea74L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741620");
    b.version(3);
    b.property("url", 0x67a6ba169d01ea81L).type(PrimitiveTypeId.STRING).origin("7468861638326741633").done();
    b.property("logo", 0x67a6ba169d01ea82L).type(PrimitiveTypeId.STRING).origin("7468861638326741634").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Project", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaecL);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741740");
    b.version(3);
    b.property("route", 0x67a6ba169d01eaf1L).type(PrimitiveTypeId.STRING).origin("7468861638326741745").done();
    b.property("title", 0x67a6ba169d01eaf2L).type(PrimitiveTypeId.STRING).origin("7468861638326741746").done();
    b.property("status", 0x67a6ba169d01eaf3L).type(MetaIdFactory.dataTypeId(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaf7L)).origin("7468861638326741747").done();
    b.property("description", 0x67a6ba169d01eaf5L).type(PrimitiveTypeId.STRING).origin("7468861638326741749").done();
    b.property("github", 0x67a6ba169d01f5eaL).type(PrimitiveTypeId.STRING).origin("7468861638326744554").done();
    b.property("access_url", 0x67a6ba169d01f5ebL).type(PrimitiveTypeId.STRING).origin("7468861638326744555").done();
    b.aggregate("videos", 0x67a6ba169d01f5f1L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5f2L).optional(true).ordered(true).multiple(true).origin("7468861638326744561").done();
    b.aggregate("technologies", 0x67a6ba169d01f5f6L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5f7L).optional(true).ordered(true).multiple(true).origin("7468861638326744566").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProjectsPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "ProjectsPage", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eae8L);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741736");
    b.version(3);
    b.aggregate("projects", 0x67a6ba169d01f5e8L).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eaecL).optional(true).ordered(true).multiple(true).origin("7468861638326744552").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQualification() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Qualification", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f604L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744580");
    b.version(3);
    b.property("title", 0x67a6ba169d01f606L).type(PrimitiveTypeId.STRING).origin("7468861638326744582").done();
    b.property("description", 0x67a6ba169d01f607L).type(PrimitiveTypeId.STRING).origin("7468861638326744583").done();
    b.property("file", 0x67a6ba169d01f608L).type(PrimitiveTypeId.STRING).origin("7468861638326744584").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQualificationsPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "QualificationsPage", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f601L);
    b.class_(false, false, false);
    b.parent(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01eab0L);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744577");
    b.version(3);
    b.aggregate("qualifications", 0x67a6ba169d01f60aL).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f604L).optional(true).ordered(true).multiple(true).origin("7468861638326744586").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSocial() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Social", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea6bL);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326741611");
    b.version(3);
    b.property("show_on_contact_form", 0x67a6ba169d01ea6fL).type(PrimitiveTypeId.BOOLEAN).origin("7468861638326741615").done();
    b.property("mail", 0x67a6ba169d01ea70L).type(PrimitiveTypeId.STRING).origin("7468861638326741616").done();
    b.aggregate("platforms", 0x67a6ba169d01ea8bL).target(0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01ea74L).optional(true).ordered(true).multiple(true).origin("7468861638326741643").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTechnology() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Technology", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5f7L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744567");
    b.version(3);
    b.property("name", 0x67a6ba169d01f5f9L).type(PrimitiveTypeId.STRING).origin("7468861638326744569").done();
    b.property("purpose", 0x67a6ba169d01f5faL).type(PrimitiveTypeId.STRING).origin("7468861638326744570").done();
    b.property("logo", 0x67a6ba169d01f5fcL).type(PrimitiveTypeId.STRING).origin("7468861638326744572").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForVideo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("PersonalPortfolio", "Video", 0x5eee97a4f53b4a19L, 0xa155bca310393580L, 0x67a6ba169d01f5f2L);
    b.class_(false, false, false);
    b.origin("r:f3f17903-e37a-4dcf-beab-4d8e1c39ad4b(PersonalPortfolio.structure)/7468861638326744562");
    b.version(3);
    b.property("video_path", 0x67a6ba169d01f5f4L).type(PrimitiveTypeId.STRING).origin("7468861638326744564").done();
    return b.create();
  }
}
